resurrection-item: minecraft:totem_of_undying

death-times:
  default: 60
  operator: 600

resurrection-times:
  default: 600
  operator: 60

messages:
  unknown-player: "???"
  will-die:
    - '&cWill die in %time%'
    - '&eOwner: %owner%'
  will-resurrect:
    - '&aWill resurrect in %time%'
    - '&eOwner: %owner%'
  bind-success: "&aSuccess!"
  bind-fail: "&cFAIL!"

resurrection-name-tag: "Immortal"

mob-blacklist:
  - minecraft:player
  - minecraft:warden
  - minecraft:wither
  - minecraft:ender_dragon
